# Uncomment the following to override menu entry labels in the "History" menu
#
# menuItemNames = {
#	ca_objects = Items
# }
# showMenu = "yes" or "no",
showMenu = "yes"

change = {
    table = "ca_occurrences", 
    type = "exhibition", 
    prevParameter = "tipo_exposicao", 
    nextParameter = "madeMACUSP", 
    values = {        
        first = {
            prev = "exposicao_mac_usp", 
            next = "exposicao_mac_usp",
            }, 
        second = {            
            prev = "exposicao_externa",  
            next = "exposicao_outras_ints",  
        }
        third = {
            prev = "exposicao_anterior_mac",
            next = "exposicao_outras_ints",  
        }, 
    },
}

