# Uncomment the following to override menu entry labels in the "History" menu
#
# menuItemNames = {
#	ca_objects = Items
# }
# showMenu = "yes" or "no",
showMenu = "yes"

change = {
    table = "ca_occurrences", 
    type = "exposição", 
    prevParameter = "tipo_exposição", 
    nextParameter = "madeMACSUP", 
    values = [
        ["Exposição produzida pelo MAC USP"               , 'MACUSP exhibitions'],  
        ["Exposição anterior à incorporação ao MAC USP"   , 'Exhibitions from other institutions'],  
        ["Exposição externa (empréstimo)"                 , 'Exhibitions from other institutions'],  
    ],
}

