# Uncomment the following to override menu entry labels in the "History" menu
#
# menuItemNames = {
#	ca_objects = Items
# }
# showMenu = "yes" or "no",
showMenu = "yes"

change = {
    table = "ca_occurrences", 
    type = "exposição", 
    prevParameter = "tipo_exposicao", 
    nextParameter = "madeMACUSP", 
    values = {        
        first = {
            prev = "Exposição produzida pelo MAC USP", 
            next = "MACUSP Exhibitions",
            }, 
        second = {            
            prev = "Exposição anterior à incorporação ao MAC USP", 
            next = "Exhibitions from other institutions",  
        }
        third = {
            prev = "Exposição externa (empréstimo)",
            next = "Exhibitions from other institutions",  
        }, 
    },
}

